### ISSUE TITLE
The Link on this sentence is incorrect 

### ISSUE THREAD

**Issue by SillyKeith** [Microsoft/windows-driver-docs#103]
The HTTPS portion of the link in this sentence is munged with the word account so that it trys to open a Store app rather than the correct web page.

For more information on how to Create a Windows Store developer account, see **Opening a developer account.**

The link should be: https://docs.microsoft.com/en-us/windows/uwp/publish/opening-a-developer-account

But instead its: **accounts**https://docs.microsoft.com/en-us/windows/uwp/publish/opening-a-developer-account

**Comment by tedhudek** [comment]
Thanks @SillyKeith for spotting this.  I made the fix, should appear on the live site momentarily.
