### ISSUE TITLE
Loading file wdfkd.dll

### ISSUE THREAD

**Issue by shauleiz** [Microsoft/windows-driver-docs#36]
Here is the correct command (SDK 10, target x64)
.load "C:\\Program Files (x86)\\Windows Kits\\10\\Debuggers\\x64\\winext\\wdfkd.dll"

**Comment by tedhudek** [comment]
Thanks @shauleiz.  Is there a specific URL you're referencing?

**Comment by shauleiz** [comment]
Sorry for being unclear.
The URL is https://msdn.microsoft.com/en-us/windows/hardware/drivers/wdf/using-the-framework-s-event-logger?f=255&MSPPError=-2147217396

Please search for the 2nd ".load" in the page

**Comment by tedhudek** [comment]
Thanks @shauleiz I have updated the page in question.  Please note that you can also submit pull requests here.  Whichever way is easier for you.  Thanks again for your suggestion!
