### ISSUE TITLE
External link to text file rather than internal link to MSDN

### ISSUE THREAD

**Issue by rpavlik** [Microsoft/windows-driver-docs#39]
This page: https://github.com/Microsoft/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/writing-a-device-installation-application.md contains the following link:

```
For more information about AutoRun, see [Creating an AutoRun-Enabled Application](http://go.microsoft.com/fwlink/p/?linkid=133162)
```

At this time, that fwlink rather unexpectedly goes to a presumably-unofficial third party site with a text file: http://ipl001.free.fr/LaboWeb/Download/MSDN-AutoRun.txt

It would appear that the internal equivalent link is https://msdn.microsoft.com/en-us/library/windows/desktop/cc144206(v=vs.85).aspx and that would probably be the desired target of the link.

In general, it would presumably be useful as part of the build (or more likely, testing) process to verify all fwlinks used in the docs to ensure validity and check them against a whitelist of destination hosts, since I just stumbled on this (and the fact that these docs are now in GitHub) by accident.

**Comment by tedhudek** [comment]
Thanks @rpavlik for spotting this and providing the correct link.  I've updated the page accordingly.
