### ISSUE TITLE
Add directions for supporting building windows 7 drivers with Enterprise WDK

### ISSUE THREAD

**Issue by dheater** [Microsoft/windows-driver-docs#64]
I've been trying to use the Enterprise WDK to build drivers and libraries that need to run on both Windows 10 and 7. I have my TargetPlatform set to 8.1.

I get errors that the 8.1 SDK is not installed. I've tried overlaying an install of SDK 8.1 on top of the EWDK, but haven't gotten success yet.

**Comment by tedhudek** [comment]
Thank you for reaching out to us. Unfortunately, we do not have the capability to provide help with your project. For that type of help, please see the resources that we list on our [Community](https://developer.microsoft.com/en-us/windows/hardware/support) page, where you will find a number of community-based and support options.
